[versions]
desugaring = "2.1.5"
agp = "8.10.1"
material = "1.12.0"
activity = "1.10.1"
app-compat = "1.7.1"
core = "1.16.0"
datastore = "1.1.7"
fragment = "1.8.8"
lifecycle = "2.9.1"
recycler-view = "1.4.0"
sqlite = "2.5.2"
test-ext = "1.2.1"
test-rules = "1.6.1"
test-runner = "1.6.2"
work = "2.10.2"
coil = "3.2.0"
leakcanary = "2.14"
hilt = "2.56.2"
hiltExt = "1.2.0"
jackson = "2.19.1"
kotlin = "2.1.21"
coroutines = "1.10.2"
datetime = "0.6.2"
serialization = "1.8.1"
ksp = "2.1.21-2.0.2"
ktor = "3.2.0"
libsu = "6.0.0"
room = "2.7.2"
shizuku = "13.0.0"
image-viewer = "v1.0.1"
junit-jupiter = "5.13.1"

[libraries]
desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugaring" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "app-compat" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
datastore-core = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
datastore-proto = { group = "androidx.datastore", name = "datastore", version.ref = "datastore" }
lifecycle-runtime= { group = "androidx.lifecycle", name = "lifecycle-runtime", version.ref = "lifecycle" }
lifecycle-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "lifecycle" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recycler-view" }
sqlite-ktx = { group = "androidx.sqlite", name = "sqlite-ktx", version.ref = "sqlite" }
test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "test-ext" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
work-testing = { group = "androidx.work", name = "work-testing", version.ref = "work" }
coil-core = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-test = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-core", version.ref = "jackson" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }
coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "coroutines" }
coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }
datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime" }
serialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor"  }
ktor-mock = { group = "io.ktor", name = "ktor-client-mock", version.ref = "ktor"  }
libsu-core = { group = "com.github.topjohnwu.libsu", name = "core", version.ref = "libsu" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-test = { group = "androidx.room", name = "room-testing", version.ref = "room" }
shizuku-api = { group = "dev.rikka.shizuku", name = "api", version.ref = "shizuku" }
shizuku-provider = { group = "dev.rikka.shizuku", name = "provider", version.ref = "shizuku" }
image-viewer = { module = "com.github.stfalcon-studio:StfalconImageViewer", version.ref = "image-viewer" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit-jupiter" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
room = ["room-runtime", "room-ktx"]
shizuku = ["shizuku-provider", "shizuku-api"]
ktor = ["ktor-core", "ktor-okhttp"]
coroutines = ["coroutines-core", "coroutines-android", "coroutines-guava"]
coil = ["coil-core", "coil-network"]
test-unit = ["junit-jupiter", "ktor-mock", "coroutines-test", "kotlin-test"]
test-android = ["test-runner", "test-rules", "test-ext", "coroutines-test", "kotlin-test"]
